/*
 * Copyright (c) 2022 by the OnMetal authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"
	json "encoding/json"
	"fmt"

	v1alpha1 "github.com/onmetal/onmetal-api-net/api/core/v1alpha1"
	corev1alpha1 "github.com/onmetal/onmetal-api-net/client-go/applyconfigurations/core/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeNetworkPolicyTargetses implements NetworkPolicyTargetsInterface
type FakeNetworkPolicyTargetses struct {
	Fake *FakeCoreV1alpha1
	ns   string
}

var networkpolicytargetsesResource = v1alpha1.SchemeGroupVersion.WithResource("networkpolicytargetses")

var networkpolicytargetsesKind = v1alpha1.SchemeGroupVersion.WithKind("NetworkPolicyTargets")

// Get takes name of the networkPolicyTargets, and returns the corresponding networkPolicyTargets object, and an error if there is any.
func (c *FakeNetworkPolicyTargetses) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.NetworkPolicyTargets, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(networkpolicytargetsesResource, c.ns, name), &v1alpha1.NetworkPolicyTargets{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.NetworkPolicyTargets), err
}

// List takes label and field selectors, and returns the list of NetworkPolicyTargetses that match those selectors.
func (c *FakeNetworkPolicyTargetses) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.NetworkPolicyTargetsList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(networkpolicytargetsesResource, networkpolicytargetsesKind, c.ns, opts), &v1alpha1.NetworkPolicyTargetsList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.NetworkPolicyTargetsList{ListMeta: obj.(*v1alpha1.NetworkPolicyTargetsList).ListMeta}
	for _, item := range obj.(*v1alpha1.NetworkPolicyTargetsList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested networkPolicyTargetses.
func (c *FakeNetworkPolicyTargetses) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(networkpolicytargetsesResource, c.ns, opts))

}

// Create takes the representation of a networkPolicyTargets and creates it.  Returns the server's representation of the networkPolicyTargets, and an error, if there is any.
func (c *FakeNetworkPolicyTargetses) Create(ctx context.Context, networkPolicyTargets *v1alpha1.NetworkPolicyTargets, opts v1.CreateOptions) (result *v1alpha1.NetworkPolicyTargets, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(networkpolicytargetsesResource, c.ns, networkPolicyTargets), &v1alpha1.NetworkPolicyTargets{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.NetworkPolicyTargets), err
}

// Update takes the representation of a networkPolicyTargets and updates it. Returns the server's representation of the networkPolicyTargets, and an error, if there is any.
func (c *FakeNetworkPolicyTargetses) Update(ctx context.Context, networkPolicyTargets *v1alpha1.NetworkPolicyTargets, opts v1.UpdateOptions) (result *v1alpha1.NetworkPolicyTargets, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(networkpolicytargetsesResource, c.ns, networkPolicyTargets), &v1alpha1.NetworkPolicyTargets{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.NetworkPolicyTargets), err
}

// Delete takes name of the networkPolicyTargets and deletes it. Returns an error if one occurs.
func (c *FakeNetworkPolicyTargetses) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(networkpolicytargetsesResource, c.ns, name, opts), &v1alpha1.NetworkPolicyTargets{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeNetworkPolicyTargetses) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(networkpolicytargetsesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.NetworkPolicyTargetsList{})
	return err
}

// Patch applies the patch and returns the patched networkPolicyTargets.
func (c *FakeNetworkPolicyTargetses) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.NetworkPolicyTargets, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(networkpolicytargetsesResource, c.ns, name, pt, data, subresources...), &v1alpha1.NetworkPolicyTargets{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.NetworkPolicyTargets), err
}

// Apply takes the given apply declarative configuration, applies it and returns the applied networkPolicyTargets.
func (c *FakeNetworkPolicyTargetses) Apply(ctx context.Context, networkPolicyTargets *corev1alpha1.NetworkPolicyTargetsApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.NetworkPolicyTargets, err error) {
	if networkPolicyTargets == nil {
		return nil, fmt.Errorf("networkPolicyTargets provided to Apply must not be nil")
	}
	data, err := json.Marshal(networkPolicyTargets)
	if err != nil {
		return nil, err
	}
	name := networkPolicyTargets.Name
	if name == nil {
		return nil, fmt.Errorf("networkPolicyTargets.Name must be provided to Apply")
	}
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(networkpolicytargetsesResource, c.ns, *name, types.ApplyPatchType, data), &v1alpha1.NetworkPolicyTargets{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.NetworkPolicyTargets), err
}
